name: Security Scan with ZAP

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: ZAP Scan with Addons
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://brainportstg.wpengine.com/'
